# Generated by Django 5.1.1 on 2024-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_list_posted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_list',
            name='job_type',
            field=models.JSONField(default=dict),
        ),
    ]
