# Generated by Django 5.1.1 on 2024-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_list_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_list',
            name='job_id',
            field=models.CharField(default='184064313115', max_length=200, unique=True),
        ),
    ]
