# Generated by Django 5.1.1 on 2024-10-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_billed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
