# Generated by Django 5.1.1 on 2024-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='billed_amount',
            field=models.CharField(blank=True, default='0.0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
