# Generated by Django 5.1.1 on 2024-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_comment_billed_amount_alter_comment_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='freelancer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
