# Generated by Django 5.1.1 on 2024-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_llmresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llmresponse',
            old_name='name',
            new_name='client_location',
        ),
        migrations.RenameField(
            model_name='llmresponse',
            old_name='data',
            new_name='other_data',
        ),
        migrations.AddField(
            model_name='llmresponse',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
